name: Create files

on:
  workflow_dispatch:
  push:
    branches:  # ignore pushed tags
      - "*"
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

permissions:
  contents: read
  pull-requests: read

jobs:
  create_files:
    name: Create files
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        gloss_lang: ['de', 'el', 'en', 'es', 'fi', 'fr', 'hr', 'it', 'ja', 'lt', 'nl', 'no', 'pl', 'pt', 'ru', 'sv', 'zh']
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install package
        run: |
          # remove mecab once "mecab-python3" releases 3.12 wheels
          sudo apt install -y lbzip2 mecab libmecab-dev
          python -m pip install .

      - name: Create files
        run: proficiency ${{ matrix.gloss_lang }}
        env:
          PYTHONOPTIMIZE: 1
          PYTHONWARNINGS: default

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.gloss_lang }}_gloss
          if-no-files-found: error
          path: |
            **/wiktionary_*.bz2
            **/kindle_*.bz2
            **/kll.*.bz2
