on:
  push:
    branches:
      - '**'
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - '**'
    paths-ignore:
      - '**.md'

name: Create files

jobs:
  create_files:
    name: Create files
    runs-on: ubuntu-latest
    strategy:
      matrix:
        gloss_lang: ["en", "zh"]
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - uses: dsaltares/fetch-gh-release-asset@master
        if: matrix.gloss_lang != 'en'
        with:
          repo: xxyzz/wiktextract
          regex: true
          file: ".*\\.tar\\.gz"

      - name: Extract Wiktionary json files
        if: matrix.gloss_lang != 'en'
        run: find . -name '*.tar.gz' -execdir tar -xzvf '{}' \;

      - name: Create files
        run: bash ./create_files.sh ${{ matrix.gloss_lang }}

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.gloss_lang }}_gloss
          path: |
            **/wiktionary_*.tar.gz
            en/kindle_lemmas_dump_*
