on:
  push:
    branches:
      - '**'
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - '**'
    paths-ignore:
      - '**.md'

name: Create files

jobs:
  create_files:
    name: Create files
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        gloss_lang: ['de', 'el', 'en', 'es', 'fi', 'fr', 'it', 'ja', 'lt', 'nl', 'no', 'pl', 'pt', 'ru', 'sv', 'zh']
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Create files
        run: bash ./create_files.sh ${{ matrix.gloss_lang }}

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.gloss_lang }}_gloss
          if-no-files-found: error
          path: |
            **/wiktionary_*.tar.gz
            **/kindle_*.tar.gz
            **/kll.*.tar.gz