name: Lint Code Base

on:
  push:
    branches:
      - '**'
    paths:
      - '**.py'
  pull_request:
    branches:
      - '**'
    paths:
      - '**.py'

jobs:
  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: python -m pip install -e .[dev]
      - run: python -m black --check .
      - run: python -m mypy -p proficiency
      - run: python -m ruff .
