name: Create Release

on:
  push:
    tags:
      - 'v*'

opermissions:
  contents: write

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yml
          commit: ${{ github.sha }}

      - uses: softprops/action-gh-release@v1
        with:
          prerelease: ${{ endsWith(github.ref_name, 'dev') }}
          files: |
            **/*.bz2
