on:
  push:
    tags:
      - 'v*'

name: Create Release

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yml

      - uses: softprops/action-gh-release@v1
        with:
          files: |
            **/*.tar.gz
            **/kindle_lemmas_dump_*
