on:
  push:
    tags:
      - 'v*'

name: Create Release

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3

      - uses: softprops/action-gh-release@v1
        with:
          files: |
            **/*.tar.gz
            en/kindle_lemmas_dump_*
